import pygame

# Screen dimensions
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Font settings
FONT_NAME = 'lucidaconsole'
FONT_SIZE = 30

# Colours (R, G, B) or (R, G, B, A) format
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
TABLE_GREEN = (22, 79, 40)
BG_DARK_GREY = (30, 30, 30)
TEXTBOX_DARK_GREY = (10, 10, 10)
TEXTBOX_LIGHT_GREY = (235, 235, 235)
SHADOW = (0, 0, 0, 15)

# Text box settings
TEXTBOX_WIDTH = 1152 # SCREEN_WIDTH * 0.9
TEXTBOX_HEIGHT = 144 # SCREEN_HEIGHT * 0.2
TEXTBOX_X = 64 # (SCREEN_WIDTH - TEXT_BOX_WIDTH) // 2
TEXTBOX_Y = 556 # SCREEN_HEIGHT - TEXT_BOX_HEIGHT - (SCREEN_HEIGHT // 36)
TEXTBOX_BORDER_RADIUS = 10

# Text settings
LINE_HEIGHT = 38
PADDING = 18
LETTER_DELAY = 10
MAX_TEXT_WIDTH = 1117 # TEXTBOX_WIDTH - LINE_HEIGHT

# Text box arrow settings
ARROW_BLINK_SPEED_MS = 500
ARROW_SIZE = 10
ARROW_X = 1186 # TEXTBOX_X + TEXTBOX_WIDTH - 30
ARROW_Y = 675 # TEXTBOX_Y + TEXTBOX_HEIGHT - 25

# Card dimensions
CARD_WIDTH = 500/4.4
CARD_HEIGHT = 726/4.4

# Card positioning
FIRST_PLAYER_CARD_X = 400
FIRST_PLAYER_CARD_Y = 350
PLAYER_CARD_DISPLACEMENT_X = 25
PLAYER_CARD_DISPLACEMENT_Y = 29
FIRST_DEALER_CARD_X = 1050
FIRST_DEALER_CARD_Y = 30
DEALER_CARD_DISPLACEMENT_X = 130
DEALER_CARD_DISPLACEMENT_Y = 0

# Scoreboard positioning
SCOREBOARD_TEXT_X = 20
SCOREBOARD_TITLE_Y = 30
SCOREBOARD_PLAYER_Y = 60
SCOREBOARD_DEALER_Y = 90

# Draw back of card
CARD_BACK = pygame.transform.smoothscale(
    pygame.image.load("assets/cards/back.png"),
    (CARD_WIDTH, CARD_HEIGHT)
)

# Music settings
MUSIC_VOLUME = 0.5
INTRO_MUSIC = "assets/music/intro.mp3"
MAIN_MUSIC = "assets/music/main.mp3"

# Sounds settings
CARD_DRAW_VOLUME = 0.3
CARD_DRAW_SOUND = "assets/sounds/card_draw.wav"
GAME_WON_VOLUME = 0.65
PLAYER_GAME_WON_SOUND = "assets/sounds/player_game_won.wav"
DEALER_GAME_WON_SOUND = "assets/sounds/dealer_game_won.wav"

