INTRO_DIALOGUE_LINES = [
    "Welcome to the blackjack table!",
    "My name is The Dealer.",
    "Today, we'll be playing some rounds of blackjack.",
    "No gambling though. I'm here to showcase the beauty, the artistry of this fine card game.",
    "Not here to partake in the devious act of gambling.",
    "Instead...",
    "Let's play the first to win 15 games.",
    "Are you familiar with the rules?",
    "...",
    "Well... let me give you a rundown on them anyway.",
    "Let's bring the table in.",
    "...", # table appears on screen
    "There we go.",
    "The rules are simple.",
    "The aim of the game is to beat me, The Dealer.",
    "Your goal is to get as close to 21 as possible, by totalling the value of the cards in your hand.",
    "Face cards are worth 10, and aces are worth either 1 or 11.",
    "You'll start with two cards.",
    "You can hit to take another card, or stand to keep what you've got.",
    "But no going over 21, otherwise you go bust and lose.",
    "Now for me, The Dealer.",
    "I also get 2 cards at the start, and I need to hit until I reach at least 17.",
    "Oh, one last thing.",
    "If you get an ace and a ten-value card straight away, that's a Blackjack, and you win!",
    "Well.. Unless I also get a blackjack... then it's a draw.",
    "...",
    "Anywhom...",
    "Let's play!"
]
